// THIS FILE WAS AUTO-GENERATED by merging http_api.cpp and task_http.cpp
// Original files kept for reference.
// Do not include http_api.h or task_http.h anymore; use "http.h".

#include <Arduino.h>
#include <ESPmDNS.h>
#include <WebServer.h>
#include "globals.h"
#include "rtos.h"
#include "http.h"
#include "portal.h"
#include "hal_time_freertos.h"
#include "http.h"
extern void handlePing();
static bool s_api_running = false;

void startApi()
{
	if (s_api_running) return;
	if(DEBUG_NET) Serial.println("[HTTP] Starting API");
	xEventGroupClearBits(g_sysEvents, EVT_PORTAL_ON);
	stopPortal();
	server.on("/api/ping", HTTP_GET, handlePing);
	server.begin();
	startHttpTask();
	MDNS.end();
	if (MDNS.begin("ledclock"))
	{
		if(DEBUG_NET) Serial.println("[HTTP] Starting MDNS");
		MDNS.setInstanceName("LED Clock");
		MDNS.addService("http", "tcp", 80);
	}
	s_api_running = true;
}


void stopApi()
{
	if (!s_api_running) return;
	stopHttpTask();
	server.stop();
	MDNS.end();
	s_api_running = false;
}


void handlePing()
{
	server.sendHeader("Access-Control-Allow-Origin", "*");
	server.sendHeader("Cache-Control", "no-store");

	unsigned long uptime = hal_millis();
	size_t freeHeap = ESP.getFreeHeap();

	String mode = "UNKNOWN";
	wifi_mode_t wm = WiFi.getMode();
	if (wm & WIFI_AP)
	{
		mode = "AP";
	}
	else if (wm & WIFI_STA)
	{
		mode = "STA";
	}

	time_t tnow = time(nullptr);
	unsigned long long now_ms = (unsigned long long)tnow * 1000ULL;

	String json = "{";
	json += "\"pong\":true,";
	json += "\"now\":" + String((unsigned long long)now_ms) + ",";
	json += "\"uptime_ms\":" + String(uptime) + ",";
	json += "\"heap_free\":" + String((unsigned long)freeHeap) + ",";
	json += "\"wifi_mode\":\"" + mode + "\"";
	json += "}";

	server.send(200, "application/json", json);
}


// ---- task_http.cpp merged below ----

#include <Arduino.h>
#include <WebServer.h>
#include "rtos.h"

extern WebServer server;

static TaskHandle_t httpTaskHandle = nullptr;

static void httpTask(void*)
{
	for (;;)
	{
		server.handleClient();

		// ~100 Hz
		vTaskDelay(pdMS_TO_TICKS(10));
	}
}


void startHttpTask()
{
	if (httpTaskHandle == nullptr)
	{
		xTaskCreatePinnedToCore(httpTask, "http", 4096, nullptr, 1, &httpTaskHandle, 1);
	}
}


void stopHttpTask()
{
	if (httpTaskHandle != nullptr)
	{
		TaskHandle_t toDelete = httpTaskHandle;
		httpTaskHandle = nullptr;
		vTaskDelete(toDelete);
	}
}
